# install-windows.ps1 — Windows installer for Clawdmeter daemon
# Uses Task Scheduler for autostart (no admin required for LOGON trigger).
param()
$ErrorActionPreference = "Stop"

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$TaskName   = "ClawdmeterDaemon"
$DaemonPy   = Join-Path $ScriptDir "daemon\claude_usage_daemon.py"
$VenvDir    = Join-Path $ScriptDir "daemon\.venv"
$LogDir     = Join-Path $env:APPDATA "Clawdmeter\Logs"
$LogOut     = Join-Path $LogDir "claude-usage-daemon.log"
$WrapperPs1 = Join-Path $ScriptDir "daemon\run-daemon-windows.ps1"

Write-Host "=== Clawdmeter Windows install ===" -ForegroundColor Cyan
Write-Host ""

# 1) Prerequisites
Write-Host "[1/4] Checking prerequisites..."
$python = (Get-Command python  -ErrorAction SilentlyContinue)?.Source
if (-not $python) { $python = (Get-Command python3 -ErrorAction SilentlyContinue)?.Source }
if (-not $python) {
    Write-Error "python not found. Install from https://python.org and add to PATH."
}
$credPath = Join-Path $env:USERPROFILE ".claude\.credentials.json"
if (-not (Test-Path $credPath)) {
    Write-Warning "~\.claude\.credentials.json not found."
    Write-Warning "Sign in via Claude Code first, then re-run this installer."
    Write-Warning "Continuing — the daemon will retry on each poll."
}
Write-Host "  OK (python: $python)"
Write-Host ""

# 2) Python virtualenv
Write-Host "[2/4] Creating Python virtualenv at daemon\.venv ..."
if (-not (Test-Path $VenvDir)) {
    & $python -m venv $VenvDir
}
$pip     = Join-Path $VenvDir "Scripts\pip.exe"
$PythonExe = Join-Path $VenvDir "Scripts\python.exe"
& $pip install --quiet --upgrade pip
& $pip install --quiet "bleak>=0.22" "httpx>=0.27"
Write-Host "  OK ($PythonExe)"
Write-Host ""

# 3) Launcher wrapper (captures stdout/stderr to a log file)
Write-Host "[3/4] Writing launcher script..."
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
@"
# Auto-generated by install-windows.ps1 — do not hand-edit.
# Redirects daemon output to the Clawdmeter log file.
`$LogOut = "$LogOut"
`$PythonExe = "$PythonExe"
`$DaemonPy = "$DaemonPy"

Start-Transcript -Path `$LogOut -Append -NoClobber:`$false
try { & `$PythonExe `$DaemonPy } finally { Stop-Transcript }
"@ | Set-Content -Encoding utf8 $WrapperPs1
Write-Host "  Launcher: $WrapperPs1"
Write-Host "  Logs:     $LogOut"
Write-Host ""

# 4) Scheduled task (runs at logon, restarts on failure)
Write-Host "[4/4] Registering scheduled task '$TaskName'..."
$pwsh = (Get-Command powershell.exe).Source
$action = New-ScheduledTaskAction `
    -Execute $pwsh `
    -Argument "-NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$WrapperPs1`"" `
    -WorkingDirectory $ScriptDir

$trigger  = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit 0 `
    -RestartCount 5 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -StartWhenAvailable

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
Register-ScheduledTask `
    -TaskName    $TaskName `
    -Action      $action `
    -Trigger     $trigger `
    -Settings    $settings `
    -Description "Clawdmeter BLE usage daemon" | Out-Null

Write-Host "  Registered."
Write-Host ""

Write-Host "=== Done ===" -ForegroundColor Green
Write-Host ""
Write-Host "The daemon will start automatically at next login."
Write-Host "To start it now:"
Write-Host "  Start-ScheduledTask -TaskName $TaskName"
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  Get-ScheduledTask $TaskName                   # check status"
Write-Host "  Start-ScheduledTask -TaskName $TaskName       # start"
Write-Host "  Stop-ScheduledTask  -TaskName $TaskName       # stop"
Write-Host "  Get-Content `"$LogOut`" -Tail 50 -Wait        # live logs"
Write-Host ""
Write-Host "First-time Bluetooth pairing:"
Write-Host "  1. Power on the device."
Write-Host "  2. Open Settings -> Bluetooth & devices."
Write-Host "  3. The daemon discovers 'Claude Controller' automatically within ~30 s."
Write-Host ""
