#!/usr/bin/env python3
"""Generate firmware/src/flame_icon.h — the burn-rate corner indicator.

Original pixel-art flame (no third-party assets), emitted as RGB565A8 the same
way the firmware's other icons are stored. Run: python tools/gen_flame.py
"""
import os
from PIL import Image, ImageDraw

SIZE = 48
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "firmware", "src", "flame_icon.h")


def _scale(pts, cx, cy, k):
    return [(cx + (x - cx) * k, cy + (y - cy) * k) for x, y in pts]


def draw_flame():
    im = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    outer = [(24,3),(30,13),(27,20),(34,25),(35,34),(30,43),(24,46),
             (18,43),(13,34),(20,27),(14,20),(20,12)]
    cx, cy = 24, 32
    d.polygon(outer, fill=(196, 58, 24, 255))                 # outer red-orange
    d.polygon(_scale(outer, cx, cy, 0.70), fill=(232, 116, 30, 255))  # orange
    d.polygon(_scale(outer, cx, cy, 0.42), fill=(246, 200, 24, 255))  # yellow
    d.ellipse([cx-4, cy-4, cx+4, cy+7], fill=(255, 244, 190, 255))    # hot core
    return im


def to_rgb565a8(im):
    px = im.load(); rgb = bytearray(); al = bytearray()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            rgb.append(v & 0xFF); rgb.append((v >> 8) & 0xFF); al.append(a)
    return bytes(rgb) + bytes(al)


def carr(b):
    return "\n".join("    " + ", ".join(f"0x{v:02X}" for v in b[i:i+16]) + ","
                     for i in range(0, len(b), 16))


def main():
    im = draw_flame()
    data = to_rgb565a8(im)
    with open(OUT, "w") as f:
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("// Original pixel-art flame for the burn-rate corner indicator.\n")
        f.write("// Generated by tools/gen_flame.py. RGB565A8.\n")
        f.write(f"#define ICON_FLAME_W {im.width}\n#define ICON_FLAME_H {im.height}\n")
        f.write(f"// {im.width*im.height} RGB565 pixels (little-endian) then alpha bytes\n")
        f.write(f"static const uint8_t icon_flame_data[{len(data)}] = {{\n{carr(data)}\n}};\n")
    print("wrote", os.path.relpath(OUT, HERE))


if __name__ == "__main__":
    main()
